security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern:            ^/admin
            form_login:
                provider:       fos_userbundle
                login_path:     sf_web_app_back_office_security_login
                use_forward:    true
                use_referer:    true
                check_path:     sf_web_app_back_office_security_check
                failure_path:   sf_web_app_back_office_bundle_admin_index
                default_target_path: sf_web_app_back_office_bundle_admin_index
            logout:
                path: sf_web_app_back_office_security_logout
                target: sf_web_app_cms_bundle_homepage
            anonymous:    true

        # defaut login area for standard users
        main:
            context: primary_auth
            pattern:            ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: fos_user_profile_show
            logout:
                path: fos_user_security_logout
                target: sf_web_app_cms_bundle_homepage
            anonymous:    true

    access_control:
        # back-office

        - { path: ^/admin/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/private-space, roles: ROLE_USER }
        # front-office
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }