# PROFILE
fos_user_profile_show:
    pattern: /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /profile/editer
    defaults: { _controller: FoulquierInfoFrontOfficeBundle:Profile:edit }
    requirements:
      _method: GET|POST