sf_web_app_cms_homepage:
    path:     /
    defaults: { _controller: SfWebAppCmsBundle:Default:index }

sf_web_app_cms_homepage:
    path:     /
    defaults: { _controller: SfWebAppCmsBundle:Default:index }
