sf_web_app_back_office_security_login:
    path:     /login
    defaults: { _controller: SfWebAppBackOfficeBundle:Security:login }

sf_web_app_back_office_security_check:
    path:     /login-check
    defaults: { _controller: SfWebAppBackOfficeBundle:Security:check }
    requirements:
        _method: POST

sf_web_app_back_office_security_logout:
    path:     /logout
    defaults: { _controller: SfWebAppBackOfficeBundle:Security:logout }